export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
export const TITLE_CHANGED = 'TITLE_CHANGED';

export const WEATHER_DATA_REQUEST = 'WEATHER_DATA_REQUEST';
export const WEATHER_DATA_FETCH = 'WEATHER_DATA_FETCH';
export const WEATHER_DATA_SUCCEEDED = 'WEATHER_DATA_SUCCEEDED';
export const WEATHER_DATA_FAILED = 'WEATHER_DATA_FAILED';

export const WEATHER_PANEL_MOUNTED = 'WEATHER_PANEL_MOUNTED';

export const GET_CURRENT_LOC = 'GET_CURRENT_LOC';
export const GET_CURRENT_LOC_FAIL = 'GET_CURRENT_LOC_FAIL';
export const GET_CURRENT_LOC_SUCCESS = 'GET_CURRENT_LOC_SUCCESS';
export const CHANGE_FETCH_OPTIONS = 'CHANGE_FETCH_OPTIONS';